OMP_NUM_THREADS=1 CUDA_VISIBLE_DEVICES=0,1,2,3 torchrun --nproc_per_node=4 --master_port 29501 main.py \
--arch resnet50 \
--num_workers 10 \
--optimizer sgd \
--lr 0.03 \
--epochs 401 \
--batch_size_per_gpu 128 \
--weight_decay 1e-4 \
--weight_decay_end 1e-4 \
--global_crops_scale 0.14 1 \
--local_crops_scale 0.05 0.14 \
--data_path /home/ljl/Datasets/ifood/ \
--k 0 \
--num_labels 50 \
--output_dir /home/ljl/Documents/our_method/model_saving/ifood_surr_0